# Generated by Django 4.2.6 on 2023-10-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image_1_product_image_2_product_image_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_1',
            field=models.CharField(max_length=500),
        ),
    ]
