# Generated by Django 4.2.6 on 2023-11-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='pays',
            field=models.CharField(default='Cameroun', max_length=300),
        ),
    ]
