# Generated by Django 4.2.6 on 2023-11-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_disponibilité'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='disponibilité',
            field=models.CharField(max_length=300),
        ),
    ]
