# Generated by Django 4.2.6 on 2023-11-09 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_disponibilité'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='disponibilité',
            new_name='disponibilite',
        ),
    ]
