# Generated by Django 4.2.6 on 2023-11-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_product_disponibilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disponibilite',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
